#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=inference
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=08:00:00
#SBATCH --output=outputs/dna_%A.out

cd $HOME/azywot/spai

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate spai

# ✅ Check CUDA availability
python - <<'EOF'
import torch
print("CUDA available?", torch.cuda.is_available())
print("Device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)
EOF

# 🤖 Runs inference using the provided model and input data
srun python -m spai infer --input '/scratch-shared/dl2_all_data/testsets/test_set_TestSet_.Trash-1000.csv' --output '/home/azywot1/azywot/spai/output' --model 'weights/spai.pth'
