#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --output="outputs/train_please_work_%A.out"
#SBATCH --partition=gpu_h100
#SBATCH --time=10:00:00
#SBATCH --mem=180G




module purge
module load 2023
module load Anaconda3/2023.07-2


# Setup 
# conda create -n spai python=3.11
conda activate spai



# cd $HOME
# # git clone https://github.com/NVIDIA/apex

# cd apex
# pip install apex



cd $HOME/spai
# pip install filetype
# conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
# pip install -r requirements.txt
# pip install open_clip_torch
# pip install jsonschema
# Inference
# srun python -m spai --help

# --amp-opt-level "O0" \
srun python -m spai train \
  --cfg "./configs/spai.yaml" \
  --batch-size 256 \
  --pretrained "weights/spai.pth" \
  --output "/scratch-shared/dl2_all_data/weights/train_chameleon_fusion_convnext" \
  --data-path "/scratch-shared/dl2_all_data/chameleon_dataset_split.csv" \
  --tag "spai_chameleon_fusion_convnext" \
  --amp-opt-level "O0" \
  --data-workers 8 \
  --save-all \
  --opt "DATA.VAL_BATCH_SIZE" "512" \
  --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
  --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
  --training-data-percentage 0.5 \
  --csv-root-dir "/" \

# --pretrained "./weights/mfm_pretrain_vit_base.pth" \ 
