#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=eval_ff
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1:00:00
#SBATCH --mem=180G
#SBATCH --hint=nomultithread
#SBATCH --output=/home/scur2605/spai/jobs/outputs/semantic/TEST-TRIPLE-FUSION%A.out

cd /home/scur2605/spai
export PYTHONPATH=/home/scur2605:$PYTHONPATH
export NEPTUNE_API_TOKEN="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjZWZkYTNkZC02Y2VmLTRjZWYtYjQwMy1kNGZiMzAwYzg3NjgifQ=="
export NEPTUNE_PROJECT="iwkooo/spai"
module purge
module load 2023
module load Anaconda3/2023.07-2

source activate spai_2

# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 8 \
# --model "/home/scur2605/spai/weights/spai.pth" \
# --output "./output/spai/test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_dalle2.csv" 

# python -m spai test \
# --cfg "./configs/spai.yaml" \z
# --batch-size 8 \
# --model "/home/scur2605/spai/output/simple/finetune/first_run/ckpt_epoch_3.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/artifact_test.csv" \
# --opt "PRINT_FREQ" "2"


# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_dalle2.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \

# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_dalle3.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \



python -m spai test \
--cfg "./configs/spai.yaml" \
--batch-size 10 \
--model "/home/scur2605/spai/output/triple-fuse/finetune/first_run/ckpt_epoch_1.pth" \
--output "./output/semantic_test" \
--tag "spai" \
--opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
--opt "DATA.NUM_WORKERS" "8" \
--opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
--opt "DATA.TEST_PREFETCH_FACTOR" "1" \
--test-csv "/home/scur2605/spai/data/test_set_gigagan.csv" \
--opt "PRINT_FREQ" "2" \
--opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \
--opt "MODEL.SEMANTIC_CONTEXT.SPAI_INPUT_SIZE" "[1024, 1024]" \


# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_midjourney-v6.1.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \



# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_sd1_4.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \



# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_sd3.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \



# python -m spai test \
# --cfg "./configs/spai.yaml" \
# --batch-size 10 \
# --model "/home/scur2605/spai/output/resnet/finetune/fused_run/ckpt_epoch_9.pth" \
# --output "./output/semantic_test" \
# --tag "spai" \
# --opt "MODEL.PATCH_VIT.MINIMUM_PATCHES" "4" \
# --opt "DATA.NUM_WORKERS" "8" \
# --opt "MODEL.FEATURE_EXTRACTION_BATCH" "400" \
# --opt "DATA.TEST_PREFETCH_FACTOR" "1" \
# --test-csv "/home/scur2605/spai/data/test_set_flux.csv" \
# --opt "PRINT_FREQ" "2" \
# --opt "MODEL.SEMANTIC_CONTEXT.HIDDEN_DIMS" "[512]" \

